pipeline{
	agent any
	stages{
		stage('build application') {
			steps{
				bat 'mvn -f java-tomcat-sample/pom.xml clean package'
			}
			post{
				success{
					echo "Now archiving artifacts"
					archiveArtifacts artifacts: '**/*.war'
				}
			}
		}
	}
}